/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks_form;

import Dao.HoaDon_Dao;
import Pojo.HoaDon_Pojo;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Le Xuan Huy
 */
public class HoaDon_Form extends javax.swing.JFrame {

    /**
     * Creates new form HoaDon_Form
     */
    Vector vheader=new Vector();
    Vector vdata=new Vector();
    HoaDon_Dao hd;
    public HoaDon_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
        hd=new HoaDon_Dao();
        vheader.add("Mã hóa đơn");
        vheader.add("Mã khách hàng");
        vheader.add("Mã nhân viên");
        vheader.add("Số ngày");
        vheader.add("Tổng hóa đơn");
        hd.LayDSHoaDon(vdata);
        jTabHoaDon.setModel(new DefaultTableModel(vdata, vheader));
        hienThiMaKH();
        hienThiMaNV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        Bxoa = new javax.swing.JButton();
        Bthoat = new javax.swing.JButton();
        MaKHJcom = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtSoNgay = new javax.swing.JTextField();
        BTimKiem = new javax.swing.JButton();
        Bsua = new javax.swing.JButton();
        Bthem = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        txtTongHD = new javax.swing.JTextField();
        Bnew = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        MNVJcom = new javax.swing.JComboBox<>();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTabHoaDon = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(0, 204, 255));

        jPanel20.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        jPanel21.setBackground(new java.awt.Color(0, 204, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tn Hóa Đơn"));
        jPanel21.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel21AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel32.setText("Mã Hóa Đơn");

        txtMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDActionPerformed(evt);
            }
        });

        Bxoa.setText("Xóa");
        Bxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BxoaActionPerformed(evt);
            }
        });

        Bthoat.setText("Thoát");
        Bthoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BthoatMouseClicked(evt);
            }
        });
        Bthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BthoatActionPerformed(evt);
            }
        });

        MaKHJcom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MaKHJcomItemStateChanged(evt);
            }
        });
        MaKHJcom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MaKHJcomMouseDragged(evt);
            }
        });
        MaKHJcom.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                MaKHJcomMouseWheelMoved(evt);
            }
        });
        MaKHJcom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaKHJcomMouseClicked(evt);
            }
        });
        MaKHJcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaKHJcomActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã Khách");

        jLabel33.setText("Số Ngày");

        txtSoNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoNgayActionPerformed(evt);
            }
        });

        BTimKiem.setText("Tìm Kiếm");
        BTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTimKiemActionPerformed(evt);
            }
        });

        Bsua.setText("Sửa");
        Bsua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BsuaMouseClicked(evt);
            }
        });
        Bsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsuaActionPerformed(evt);
            }
        });

        Bthem.setText("Thêm");
        Bthem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BthemMouseClicked(evt);
            }
        });
        Bthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BthemActionPerformed(evt);
            }
        });

        jLabel35.setText("Tổng HD");

        txtTongHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongHDActionPerformed(evt);
            }
        });

        Bnew.setText("New");
        Bnew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BnewMouseClicked(evt);
            }
        });
        Bnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnewActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã Nhân Viên");

        MNVJcom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MNVJcomItemStateChanged(evt);
            }
        });
        MNVJcom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MNVJcomMouseDragged(evt);
            }
        });
        MNVJcom.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                MNVJcomMouseWheelMoved(evt);
            }
        });
        MNVJcom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MNVJcomMouseClicked(evt);
            }
        });
        MNVJcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNVJcomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(Bthem, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(Bnew, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(Bsua, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel21Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(MNVJcom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel21Layout.createSequentialGroup()
                                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel35))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MaKHJcom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSoNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTongHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(BTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(Bxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(Bthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTimKiem))
                .addGap(21, 21, 21)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MaKHJcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(MNVJcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtSoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bxoa)
                    .addComponent(Bthoat))
                .addGap(42, 42, 42)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bthem)
                    .addComponent(Bsua)
                    .addComponent(Bnew))
                .addGap(21, 21, 21))
        );

        jTabHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabHoaDon.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabHoaDonAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTabHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabHoaDonMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTabHoaDon);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("HÓA ĐƠN");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDActionPerformed

    private void BxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BxoaActionPerformed
        
        int pos=jTabHoaDon.getSelectedRow();
        HoaDon_Pojo x = new HoaDon_Pojo(txtMaHD.getText());
        hd.XoaHoaDon(x,pos);
        hd.LayDSHoaDon(vdata);
        jTabHoaDon.updateUI();
        JOptionPane.showMessageDialog(this, "Xóa Thành Công");
    }//GEN-LAST:event_BxoaActionPerformed

    private void BthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BthoatActionPerformed
        // TODO add your handling code here:
        Menu next = new Menu();
        next.setVisible(true);
        
    }//GEN-LAST:event_BthoatActionPerformed

    private void MaKHJcomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MaKHJcomItemStateChanged
        
        // TODO add your handling code here:
    }//GEN-LAST:event_MaKHJcomItemStateChanged

    private void MaKHJcomMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaKHJcomMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_MaKHJcomMouseDragged

    private void MaKHJcomMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_MaKHJcomMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_MaKHJcomMouseWheelMoved

    private void MaKHJcomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaKHJcomMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_MaKHJcomMouseClicked

    private void MaKHJcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaKHJcomActionPerformed

    }//GEN-LAST:event_MaKHJcomActionPerformed

    private void jPanel21AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel21AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel21AncestorAdded

    private void jTabHoaDonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabHoaDonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabHoaDonAncestorAdded

    private void jTabHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabHoaDonMouseClicked
        // TODO add your handling code here:try{
        int i = jTabHoaDon.getSelectedRow();
        TableModel model = jTabHoaDon.getModel();
        txtMaHD.setText(model.getValueAt(i, 0).toString());
        MaKHJcom.setSelectedItem(model.getValueAt(i, 1).toString());
        MNVJcom.setSelectedItem(model.getValueAt(i, 2).toString());
        txtSoNgay.setText(model.getValueAt(i, 3).toString());
        txtTongHD.setText(model.getValueAt(i, 4).toString());    
            
    }//GEN-LAST:event_jTabHoaDonMouseClicked

    private void txtSoNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoNgayActionPerformed

    private void BthoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BthoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BthoatMouseClicked

    private void BTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTimKiemActionPerformed
        // TODO add your handling code here:
        String timMaHD=txtMaHD.getText();
        hd.FindMaHD(vdata,timMaHD);
        jTabHoaDon.updateUI();
        JOptionPane.showMessageDialog(this, "Tìm thành công");
        
    }//GEN-LAST:event_BTimKiemActionPerformed

    private void BsuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BsuaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BsuaMouseClicked

    private void BsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsuaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        KtraRong(sb);
        KtraSoNgayVaTongHD(sb);
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } 
        else
        {
            String MaKH=(String) MaKHJcom.getSelectedItem();
            String MaNV=(String) MNVJcom.getSelectedItem();
            int soNgay= Integer.parseInt(txtSoNgay.getText());
            HoaDon_Pojo x = new HoaDon_Pojo(txtMaHD.getText(), MaKH, MaNV, 
                    soNgay);
            hd.SuaHD(x);
            hd.LayDSHoaDon(vdata);
            jTabHoaDon.updateUI(); 
            JOptionPane.showMessageDialog(this, "Sửa Thành Công");
        }
    }//GEN-LAST:event_BsuaActionPerformed

    private void BthemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BthemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BthemMouseClicked

    private void BthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BthemActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        KtraRong(sb);
        KtraSoNgayVaTongHD(sb);
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String MaKH = (String) MaKHJcom.getSelectedItem();
            String MaNV = (String) MNVJcom.getSelectedItem();
            int soNgay = Integer.parseInt(txtSoNgay.getText());
            int tongHD = Integer.parseInt(txtTongHD.getText());
            HoaDon_Pojo x = new HoaDon_Pojo(txtMaHD.getText(), MaKH, MaNV,
                    soNgay, tongHD);
            hd.ThemHD(x);
            hd.LayDSHoaDon(vdata);
            jTabHoaDon.updateUI();
            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
        }
    }//GEN-LAST:event_BthemActionPerformed

    private void KtraRong(StringBuilder sb) {
        if(txtMaHD.getText().trim().equals(""))
            sb.append("Mã không được để trống\n");
        if(txtSoNgay.getText().trim().equals(""))
            sb.append("Số ngày không được để trống\n");
        if(txtTongHD.getText().trim().equals(""))
            sb.append("Tổng hóa đơn không được để trống\n");
    }
    
    private void KtraSoNgayVaTongHD(StringBuilder sb) {
        try {
            int soNgay = Integer.parseInt(txtSoNgay.getText());
            double tongHD = Double.parseDouble(txtTongHD.getText());
            if(soNgay<0)
                sb.append("Số Ngày không hợp lệ (phải lớn hơn 0)\n");
            if(tongHD<0)
                sb.append("Tổng hóa đơn không hợp lệ (phải lớn hơn 0)\n");
        } catch (Exception e) {
            sb.append("Dữ liệu không hợp lệ (phải là giá trị số)\n");
        }
    }
    private void BnewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BnewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BnewMouseClicked

    private void BnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnewActionPerformed
        // TODO add your handling code here:
        txtMaHD.setText("");
        txtSoNgay.setText("");
        txtTongHD.setText("");
        txtMaHD.requestFocus();
    }//GEN-LAST:event_BnewActionPerformed

    private void MNVJcomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MNVJcomItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_MNVJcomItemStateChanged

    private void MNVJcomMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MNVJcomMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_MNVJcomMouseDragged

    private void MNVJcomMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_MNVJcomMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_MNVJcomMouseWheelMoved

    private void MNVJcomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MNVJcomMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MNVJcomMouseClicked

    private void MNVJcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNVJcomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MNVJcomActionPerformed

    private void txtTongHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongHDActionPerformed
    
    public void hienThiMaKH() {
        try {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=QLKS;user=sa;password=1";
            Connection conn = DriverManager.getConnection(dbURL);
            Statement st = conn.createStatement();
            String sql = "SELECT MAKH FROM KHACHHANG ";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                MaKHJcom.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println("ở đây");
        }
    }
    
     public void hienThiMaNV() {
        try {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=QLKS;user=sa;password=1";
            Connection conn = DriverManager.getConnection(dbURL);
            Statement st = conn.createStatement();
            String sql = "SELECT MANV FROM NHANVIEN ";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                MNVJcom.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println("ở đây");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDon_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDon_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDon_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDon_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDon_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTimKiem;
    private javax.swing.JButton Bnew;
    private javax.swing.JButton Bsua;
    private javax.swing.JButton Bthem;
    private javax.swing.JButton Bthoat;
    private javax.swing.JButton Bxoa;
    private javax.swing.JComboBox<String> MNVJcom;
    private javax.swing.JComboBox<String> MaKHJcom;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTabHoaDon;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtSoNgay;
    private javax.swing.JTextField txtTongHD;
    // End of variables declaration//GEN-END:variables
}
