/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks_form;

import Dao.Phong_Dao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import pojo.Phong_Pojo;

/**
 *
 * @author Le Xuan Huy
 */
public class Phong_From extends javax.swing.JFrame {

    /**
     * Creates new form Phong
     */
    Vector vheader=new Vector();
    Vector vdata=new Vector();
     Dao.Phong_Dao ph;
    public Phong_From() {
        initComponents();
        this.setLocationRelativeTo(null);
        ph=new Phong_Dao();
        vheader.add("Mã phòng");
        vheader.add("Tên phòng");
        vheader.add("Loại phòng");
        vheader.add("Giá phòng");
        vheader.add("Tình trạng");
        vheader.add("Ghi chú");
        ph.LayDSPhong(vdata);
        jTabPhong.setModel(new DefaultTableModel(vdata, vheader));
        hienThiPhongCon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTabPhong = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtMaP = new javax.swing.JTextField();
        txtTenP = new javax.swing.JTextField();
        txtGiaPhong = new javax.swing.JTextField();
        Bthem = new javax.swing.JButton();
        Bsua = new javax.swing.JButton();
        Bxoa = new javax.swing.JButton();
        Bthoat = new javax.swing.JButton();
        Bnew = new javax.swing.JButton();
        jComLoaiPH = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtTinhTrang = new javax.swing.JTextField();
        txtchuThich = new javax.swing.JTextField();
        BTimPhongTrong = new javax.swing.JButton();
        BTimLoaiPhong = new javax.swing.JButton();
        txtTimPhong = new javax.swing.JTextField();
        BdatPhong = new javax.swing.JButton();
        JcomPH = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(51, 204, 255));

        jPanel17.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        jTabPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabPhongMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTabPhong);

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Phòng"));

        jLabel23.setText("Mã Phòng");

        jLabel24.setText("Tên Phòng");

        jLabel25.setText("Loại Phòng");

        jLabel26.setText("Giá Phòng");

        jLabel27.setText("Chú Thích");

        Bthem.setText("Thêm");
        Bthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BthemActionPerformed(evt);
            }
        });

        Bsua.setText("Sửa");
        Bsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsuaActionPerformed(evt);
            }
        });

        Bxoa.setText("Xóa");
        Bxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BxoaActionPerformed(evt);
            }
        });

        Bthoat.setText("Thoát");
        Bthoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BthoatMouseClicked(evt);
            }
        });
        Bthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BthoatActionPerformed(evt);
            }
        });

        Bnew.setText("New");
        Bnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnewActionPerformed(evt);
            }
        });

        jComLoaiPH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đơn", "Đôi", "VIP" }));

        jLabel1.setText("Tình Trạng");

        txtTinhTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinhTrangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel18Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(jComLoaiPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel18Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(txtMaP))
                                    .addGroup(jPanel18Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(txtTenP))
                                    .addGroup(jPanel18Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTinhTrang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtchuThich, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Bxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bthem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(Bsua, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Bnew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bthoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtMaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtTenP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jComLoaiPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel27))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtchuThich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bthem)
                            .addComponent(Bnew)))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Bsua)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bxoa)
                    .addComponent(Bthoat))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        BTimPhongTrong.setBackground(new java.awt.Color(255, 102, 0));
        BTimPhongTrong.setText("Tìm Phòng còn Trống");
        BTimPhongTrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTimPhongTrongActionPerformed(evt);
            }
        });

        BTimLoaiPhong.setBackground(new java.awt.Color(255, 102, 0));
        BTimLoaiPhong.setText("Tìm Theo loại phòng");
        BTimLoaiPhong.setToolTipText("");
        BTimLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTimLoaiPhongActionPerformed(evt);
            }
        });

        txtTimPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimPhongMouseClicked(evt);
            }
        });

        BdatPhong.setBackground(new java.awt.Color(255, 102, 0));
        BdatPhong.setText("Đặt Phòng");
        BdatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdatPhongActionPerformed(evt);
            }
        });

        JcomPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomPHActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel2.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("QUẢN LÝ PHÒNG");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTimPhong)
                                    .addComponent(JcomPH, 0, 144, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BdatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(BTimLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTimPhongTrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(300, 300, 300))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTimLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTimPhongTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTimPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BdatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JcomPH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabPhongMouseClicked
        // TODO add your handling code here:
       //DisplayDetails(((JTable)evt.getSource()).getSelectedRow());
        int i = jTabPhong.getSelectedRow();
        TableModel model = jTabPhong.getModel();        
        txtMaP.setText(model.getValueAt(i, 0).toString());
        txtTenP.setText(model.getValueAt(i, 1).toString());       
        jComLoaiPH.setSelectedItem(model.getValueAt(i, 2).toString());  
        txtGiaPhong.setText(model.getValueAt(i, 3).toString());
        txtTinhTrang.setText(model.getValueAt(i, 4).toString());
        txtchuThich.setText(model.getValueAt(i, 5).toString());
       

    }//GEN-LAST:event_jTabPhongMouseClicked

    private void BthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BthemActionPerformed
        StringBuilder sb = new StringBuilder();
        KtraRong(sb);
        KtraGiaPhong(sb);
        if(sb.length()>0)
            JOptionPane.showMessageDialog(this, sb.toString(),"Lỗi",JOptionPane.ERROR_MESSAGE);
        else
        {
            String giaPhong_str =txtGiaPhong.getText();
            Double giaPhong = Double.parseDouble(giaPhong_str);
            String loaiPhong=(String) jComLoaiPH.getSelectedItem();
            Phong_Pojo x = new Phong_Pojo(txtMaP.getText(),txtTenP.getText(),
                    loaiPhong,giaPhong,txtchuThich.getText(),txtTinhTrang.getText());
            ph.ThemPhong(x);
            ph.LayDSPhong(vdata);
            jTabPhong.updateUI();
            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
        }
    }//GEN-LAST:event_BthemActionPerformed

    private void KtraRong(StringBuilder sb) {
        if(txtMaP.getText().trim().equals(""))
            sb.append("Mã không được để trống\n");
        if(txtTenP.getText().trim().equals(""))
            sb.append("Tên không được để trống\n");
        if(txtGiaPhong.getText().trim().equals(""))
            sb.append("Giá phòng không được để trống\n");
        if(txtTinhTrang.getText().trim().equals(""))
            sb.append("Tình trạng không được để trống\n");
        if(txtchuThich.getText().trim().equals(""))
            sb.append("Chú thích không được để trống\n");
    }
    
    private void KtraGiaPhong(StringBuilder sb) {
        try {
            double giaPhong = Double.parseDouble(txtGiaPhong.getText());
            if(giaPhong<0)
                sb.append("Giá phòng không hợp lệ (phải lớn hơn 0)\n");
        } catch (Exception e) {
            sb.append("Giá phòng không hợp lệ (phải là giá trị số)\n");
        }
    }
    private void BsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsuaActionPerformed
        StringBuilder sb = new StringBuilder();
        KtraRong(sb);
        KtraGiaPhong(sb);
        if(sb.length()>0)
            JOptionPane.showMessageDialog(this, sb.toString(),"Lỗi",JOptionPane.ERROR_MESSAGE);
        else
        {
            String giaPhong_str =txtGiaPhong.getText();
            Double giaPhong = Double.parseDouble(giaPhong_str);
            String loaiPhong=(String) jComLoaiPH.getSelectedItem();
            Phong_Pojo x = new Phong_Pojo(txtMaP.getText(),txtTenP.getText(),
                    loaiPhong,giaPhong,txtchuThich.getText(),txtTinhTrang.getText());
            ph.SuaPhong(x);
            ph.LayDSPhong(vdata);
            jTabPhong.updateUI();
            JOptionPane.showMessageDialog(this, "Sửa Thành Công");
        }
    }//GEN-LAST:event_BsuaActionPerformed

    private void BxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BxoaActionPerformed
        int pos=this.jTabPhong.getSelectedRow();
        Phong_Pojo x = new Phong_Pojo(txtMaP.getText());
         ph.XoaPhong(x,pos);
        ph.LayDSPhong(vdata);
        jTabPhong.updateUI();
        JOptionPane.showMessageDialog(this, "Xóa Thành Công");
    }//GEN-LAST:event_BxoaActionPerformed

    private void BthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BthoatActionPerformed
        // TODO add your handling code here:
        Menu next = new Menu();
        next.setVisible(true);
    }//GEN-LAST:event_BthoatActionPerformed

    private void BnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnewActionPerformed
        // TODO add your handling code here:
        txtMaP.setText("");
        txtTenP.setText("");
        txtGiaPhong.setText("");
        txtTinhTrang.setText("");
        txtchuThich.setText("");
        txtMaP.requestFocus();
    }//GEN-LAST:event_BnewActionPerformed

    private void BTimPhongTrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTimPhongTrongActionPerformed
     // TODO add your handling code here:
        String phongTrong="1";
        ph.FindPhongTrong(vdata,phongTrong);
        jTabPhong.updateUI();
    }//GEN-LAST:event_BTimPhongTrongActionPerformed

    private void BTimLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTimLoaiPhongActionPerformed
        String timPhong=txtTimPhong.getText();
        ph.FindPhong(vdata,timPhong);
        jTabPhong.updateUI();
    }//GEN-LAST:event_BTimLoaiPhongActionPerformed

    private void txtTimPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimPhongMouseClicked

    }//GEN-LAST:event_txtTimPhongMouseClicked

    
    public void hienThiPhongCon() {
        try {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=QLKS;user=sa;password=1";
            Connection conn = DriverManager.getConnection(dbURL);
            Statement st = conn.createStatement();
            String sql = " SELECT * FROM PHONG WHERE TINHTRANG='1'";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                JcomPH.addItem(rs.getString(1));
            }

        } catch (Exception e) {
            System.out.println("sai ket noi");
        }
    }
    private void BdatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdatPhongActionPerformed
        String MaPhong=(String) JcomPH.getSelectedItem();
        Phong_Pojo x = new Phong_Pojo(MaPhong);
        ph.DatPhong(x);
        ph.LayDSPhong(vdata);
        jTabPhong.updateUI();
        JOptionPane.showMessageDialog(this, "Đặt phòng thành công");

    }//GEN-LAST:event_BdatPhongActionPerformed

    private void JcomPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomPHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcomPHActionPerformed

    private void txtTinhTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinhTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTinhTrangActionPerformed

    private void BthoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BthoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BthoatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Phong_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Phong_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Phong_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Phong_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Phong_From().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTimLoaiPhong;
    private javax.swing.JButton BTimPhongTrong;
    private javax.swing.JButton BdatPhong;
    private javax.swing.JButton Bnew;
    private javax.swing.JButton Bsua;
    private javax.swing.JButton Bthem;
    private javax.swing.JButton Bthoat;
    private javax.swing.JButton Bxoa;
    private javax.swing.JComboBox<String> JcomPH;
    private javax.swing.JComboBox<String> jComLoaiPH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTabPhong;
    private javax.swing.JTextField txtGiaPhong;
    private javax.swing.JTextField txtMaP;
    private javax.swing.JTextField txtTenP;
    private javax.swing.JTextField txtTimPhong;
    private javax.swing.JTextField txtTinhTrang;
    private javax.swing.JTextField txtchuThich;
    // End of variables declaration//GEN-END:variables
}
